/*
 * TwCheckoutPanel.java
 * Author  Winston Prakash
 */

package com.nayaware.twproto.ui;

import javax.swing.*;
import java.util.*;

public class TwCheckoutPanel extends javax.swing.JPanel {
	Vector fileList = null;

	/** Creates new form TwCheckoutPanel */
	public TwCheckoutPanel() {
		initComponents();
	}

	public void setFileList(Vector fileList1, Vector fileList2) {
		fileList = fileList1;
		lstFiles.setListData(fileList1);
	}

	public Vector getSelectedFiles() {
		Vector selFiles = new Vector();
		int[] selIndices = lstFiles.getSelectedIndices();
		for (int i = 0; i < selIndices.length; i++)
			selFiles.add(fileList.get(i));
		return selFiles;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {// GEN-BEGIN:initComponents
		listPanel = new javax.swing.JPanel();
		lblList = new javax.swing.JLabel();
		lstScrollPane = new javax.swing.JScrollPane();
		lstFiles = new javax.swing.JList();
		btnSelectAll = new javax.swing.JButton();
		btnUnselectAll = new javax.swing.JButton();

		setLayout(new java.awt.GridBagLayout());
		java.awt.GridBagConstraints gridBagConstraints1;

		listPanel.setLayout(new java.awt.GridBagLayout());
		java.awt.GridBagConstraints gridBagConstraints2;

		lblList.setText("Checkout File List");
		gridBagConstraints2 = new java.awt.GridBagConstraints();
		gridBagConstraints2.gridx = 1;
		gridBagConstraints2.gridy = 0;
		gridBagConstraints2.insets = new java.awt.Insets(0, 4, 0, 0);
		gridBagConstraints2.anchor = java.awt.GridBagConstraints.WEST;
		listPanel.add(lblList, gridBagConstraints2);

		lstScrollPane.setPreferredSize(new java.awt.Dimension(250, 100));
		lstScrollPane.setMinimumSize(new java.awt.Dimension(250, 150));
		lstScrollPane.setViewportView(lstFiles);

		gridBagConstraints2 = new java.awt.GridBagConstraints();
		gridBagConstraints2.gridx = 1;
		gridBagConstraints2.gridy = 1;
		gridBagConstraints2.gridheight = 2;
		gridBagConstraints2.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints2.insets = new java.awt.Insets(0, 4, 0, 0);
		listPanel.add(lstScrollPane, gridBagConstraints2);

		btnSelectAll.setText("Unselect All");
		btnSelectAll.setMargin(new java.awt.Insets(2, 5, 2, 5));
		gridBagConstraints2 = new java.awt.GridBagConstraints();
		gridBagConstraints2.gridx = 2;
		gridBagConstraints2.gridy = 2;
		gridBagConstraints2.insets = new java.awt.Insets(3, 4, 0, 0);
		gridBagConstraints2.anchor = java.awt.GridBagConstraints.NORTH;
		listPanel.add(btnSelectAll, gridBagConstraints2);

		btnUnselectAll.setText("Select All");
		btnUnselectAll.setMargin(new java.awt.Insets(2, 5, 2, 5));
		gridBagConstraints2 = new java.awt.GridBagConstraints();
		gridBagConstraints2.gridx = 2;
		gridBagConstraints2.gridy = 1;
		gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints2.insets = new java.awt.Insets(0, 4, 0, 0);
		gridBagConstraints2.anchor = java.awt.GridBagConstraints.NORTH;
		listPanel.add(btnUnselectAll, gridBagConstraints2);

		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 1;
		gridBagConstraints1.gridy = 0;
		gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
		add(listPanel, gridBagConstraints1);

	}// GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel listPanel;
	private javax.swing.JLabel lblList;
	private javax.swing.JScrollPane lstScrollPane;
	private javax.swing.JList lstFiles;
	private javax.swing.JButton btnSelectAll;
	private javax.swing.JButton btnUnselectAll;

	// End of variables declaration//GEN-END:variables
	public static void main(String[] args) {
		TwActionDialog dialog = new TwActionDialog(new javax.swing.JFrame(),
				true);
		dialog.setUserPanel(new TwCheckoutPanel());
		dialog.pack();
		dialog.show();
	}
}
