/*
 * TwCheckinPanel.java
 * Author  Winston Prakash
 */

package com.nayaware.twproto.ui;

import javax.swing.*;
import java.util.*;

public class TwCheckinPanel extends javax.swing.JPanel {

	Vector fileList = null;

	/** Creates new form TwCheckinPanel */
	public TwCheckinPanel() {
		initComponents();
		listPanel.setVisible(false);
	}

	public void setFileList(Vector fileList1, Vector fileList2) {
		fileList = fileList1;
		if (fileList1.size() > 1) {
			listPanel.setVisible(true);
			lstFiles.setListData(fileList1);
		}
	}

	public Vector getSelectedFiles() {
		Vector selFiles = new Vector();
		int[] selIndices = lstFiles.getSelectedIndices();
		for (int i = 0; i < selIndices.length; i++)
			selFiles.add(fileList.get(i));
		return selFiles;
	}

	public String getComment() {
		return txtComment.getText();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {// GEN-BEGIN:initComponents
		txtComment = new javax.swing.JTextArea();
		lblCommentl = new javax.swing.JLabel();
		listPanel = new javax.swing.JPanel();
		lblList = new javax.swing.JLabel();
		listScrollPane = new javax.swing.JScrollPane();
		lstFiles = new javax.swing.JList();
		btnDeselectAll = new javax.swing.JButton();
		btnSelectAll = new javax.swing.JButton();

		setLayout(new java.awt.GridBagLayout());
		java.awt.GridBagConstraints gridBagConstraints1;

		setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5,
				5, 5)));
		txtComment.setColumns(35);
		txtComment.setRows(5);
		txtComment.setBorder(new javax.swing.border.BevelBorder(
				javax.swing.border.BevelBorder.LOWERED));
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 1;
		gridBagConstraints1.gridy = 1;
		gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints1.insets = new java.awt.Insets(1, 3, 0, 0);
		add(txtComment, gridBagConstraints1);

		lblCommentl.setText("Comment");
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 1;
		gridBagConstraints1.anchor = java.awt.GridBagConstraints.NORTH;
		add(lblCommentl, gridBagConstraints1);

		listPanel.setLayout(new java.awt.GridBagLayout());
		java.awt.GridBagConstraints gridBagConstraints2;

		lblList.setText("Checkin File List");
		gridBagConstraints2 = new java.awt.GridBagConstraints();
		gridBagConstraints2.gridx = 1;
		gridBagConstraints2.gridy = 0;
		gridBagConstraints2.insets = new java.awt.Insets(0, 4, 0, 0);
		gridBagConstraints2.anchor = java.awt.GridBagConstraints.WEST;
		listPanel.add(lblList, gridBagConstraints2);

		listScrollPane.setPreferredSize(new java.awt.Dimension(250, 100));
		listScrollPane.setMinimumSize(new java.awt.Dimension(250, 150));
		listScrollPane.setViewportView(lstFiles);

		gridBagConstraints2 = new java.awt.GridBagConstraints();
		gridBagConstraints2.gridx = 1;
		gridBagConstraints2.gridy = 1;
		gridBagConstraints2.gridheight = 2;
		gridBagConstraints2.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints2.insets = new java.awt.Insets(0, 4, 0, 0);
		listPanel.add(listScrollPane, gridBagConstraints2);

		btnDeselectAll.setText("Unselect All");
		btnDeselectAll.setMargin(new java.awt.Insets(2, 5, 2, 5));
		btnDeselectAll.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDeselectAllActionPerformed(evt);
			}
		});

		gridBagConstraints2 = new java.awt.GridBagConstraints();
		gridBagConstraints2.gridx = 2;
		gridBagConstraints2.gridy = 2;
		gridBagConstraints2.insets = new java.awt.Insets(3, 4, 0, 0);
		gridBagConstraints2.anchor = java.awt.GridBagConstraints.NORTH;
		listPanel.add(btnDeselectAll, gridBagConstraints2);

		btnSelectAll.setText("Select All");
		btnSelectAll.setMargin(new java.awt.Insets(2, 5, 2, 5));
		gridBagConstraints2 = new java.awt.GridBagConstraints();
		gridBagConstraints2.gridx = 2;
		gridBagConstraints2.gridy = 1;
		gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints2.insets = new java.awt.Insets(0, 4, 0, 0);
		gridBagConstraints2.anchor = java.awt.GridBagConstraints.NORTH;
		listPanel.add(btnSelectAll, gridBagConstraints2);

		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 1;
		gridBagConstraints1.gridy = 0;
		gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
		add(listPanel, gridBagConstraints1);

	}// GEN-END:initComponents

	private void btnDeselectAllActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeselectAllActionPerformed
		// Add your handling code here:
	}// GEN-LAST:event_btnDeselectAllActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextArea txtComment;
	private javax.swing.JLabel lblCommentl;
	private javax.swing.JPanel listPanel;
	private javax.swing.JLabel lblList;
	private javax.swing.JScrollPane listScrollPane;
	private javax.swing.JList lstFiles;
	private javax.swing.JButton btnDeselectAll;
	private javax.swing.JButton btnSelectAll;

	// End of variables declaration//GEN-END:variables

	public static void main(String[] args) {
		TwActionDialog dialog = new TwActionDialog(new javax.swing.JFrame(),
				true);
		dialog.setUserPanel(new TwCheckinPanel());
		dialog.pack();
		dialog.show();
	}
}
