/*
 * TwDeleteWorkspacePanel.java
 * Author  Winston Prakash
 */

package com.nayaware.twproto.ui;

import javax.swing.*;
import java.util.*;

import com.nayaware.twproto.dataobjects.*;

public class TwDeleteWorkspacePanel extends javax.swing.JPanel {

	Vector wsList = null;
	TwWorkspace workspace;

	public static final int ENTIRE_WORKSPACE = 1;
	public static final int META_DATA_ONLY = 2;

	protected int deleteType = META_DATA_ONLY;

	/** Creates new form TwDeleteWorkspacePanel */
	public TwDeleteWorkspacePanel() {
		initComponents();
		lblWorkspace.setVisible(false);
		rbMetaDataOnly.setSelected(true);
	}

	public void setWorkspace(TwWorkspace ws) {
		workspace = ws;
		lblWorkspace.setVisible(true);
		lblWorkspace.setText("Delete Workspace " + workspace.getPath());
		listPanel.setVisible(false);
	}

	public TwWorkspace getWorkspace() {
		return workspace;
	}

	public void setWorkspaceList(Vector wsl) {
		wsList = wsl;
		if (wsList.size() > 1) {
			listPanel.setVisible(true);
			lstWs.setListData(wsList);
		} else {
			setWorkspace((TwWorkspace) wsList.get(0));
		}

	}

	public Vector getSelectedWorkspaces() {
		Vector selWorkspaces = new Vector();
		int[] selIndices = lstWs.getSelectedIndices();
		for (int i = 0; i < selIndices.length; i++)
			selWorkspaces.add(wsList.get(i));
		return selWorkspaces;
	}

	public int getDeleteType() {
		return deleteType;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {// GEN-BEGIN:initComponents
		btnGroup = new javax.swing.ButtonGroup();
		rbEntireWorkspace = new javax.swing.JRadioButton();
		rbMetaDataOnly = new javax.swing.JRadioButton();
		listPanel = new javax.swing.JPanel();
		scrollPane = new javax.swing.JScrollPane();
		lstWs = new javax.swing.JList();
		lblQuestion = new javax.swing.JLabel();
		lblWorkspace = new javax.swing.JLabel();

		setLayout(new java.awt.GridBagLayout());
		java.awt.GridBagConstraints gridBagConstraints1;

		setBorder(new javax.swing.border.EtchedBorder());
		rbEntireWorkspace.setText("Entire Workspace");
		btnGroup.add(rbEntireWorkspace);
		rbEntireWorkspace.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				rbEntireWorkspaceItemStateChanged(evt);
			}
		});

		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 2;
		gridBagConstraints1.gridwidth = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
		add(rbEntireWorkspace, gridBagConstraints1);

		rbMetaDataOnly.setText("Meta Data Only");
		btnGroup.add(rbMetaDataOnly);
		rbMetaDataOnly.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				rbMetaDataOnlyItemStateChanged(evt);
			}
		});

		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 3;
		gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
		add(rbMetaDataOnly, gridBagConstraints1);

		listPanel.setLayout(new java.awt.BorderLayout());

		listPanel.setBorder(new javax.swing.border.EmptyBorder(
				new java.awt.Insets(5, 5, 5, 5)));
		scrollPane.setViewportView(lstWs);

		listPanel.add(scrollPane, java.awt.BorderLayout.CENTER);

		lblQuestion.setText("Delete Listed Workspaces?");
		lblQuestion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		listPanel.add(lblQuestion, java.awt.BorderLayout.NORTH);

		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 1;
		gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
		add(listPanel, gridBagConstraints1);

		lblWorkspace.setText("Remove Workspace ");
		lblWorkspace.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 0;
		gridBagConstraints1.anchor = java.awt.GridBagConstraints.WEST;
		add(lblWorkspace, gridBagConstraints1);

	}// GEN-END:initComponents

	private void rbMetaDataOnlyItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_rbMetaDataOnlyItemStateChanged
		if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED)
			deleteType = META_DATA_ONLY;
	}// GEN-LAST:event_rbMetaDataOnlyItemStateChanged

	private void rbEntireWorkspaceItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_rbEntireWorkspaceItemStateChanged
		if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED)
			deleteType = ENTIRE_WORKSPACE;
	}// GEN-LAST:event_rbEntireWorkspaceItemStateChanged

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.ButtonGroup btnGroup;
	private javax.swing.JRadioButton rbEntireWorkspace;
	private javax.swing.JRadioButton rbMetaDataOnly;
	private javax.swing.JPanel listPanel;
	private javax.swing.JScrollPane scrollPane;
	private javax.swing.JList lstWs;
	private javax.swing.JLabel lblQuestion;
	private javax.swing.JLabel lblWorkspace;

	// End of variables declaration//GEN-END:variables
	public static void main(String[] args) {
		TwActionDialog actionDialog = new TwActionDialog(new JFrame(), true);
		TwDeleteWorkspacePanel trPanel = new TwDeleteWorkspacePanel();
		trPanel.setWorkspace(new com.nayaware.twproto.dataobjects.TwWorkspaceObject(
				"C:\\Test\\ws2"));
		actionDialog.setUserPanel(trPanel);
		actionDialog.show();
		// System.out.println(trPanel.getSelection());
	}
}
