/*
 * TwLoadChildrenPanel.java
 * Author  Winston Prakash
 */

package com.nayaware.twproto.ui;

import javax.swing.*;
import java.io.*;
import java.util.*;

import com.nayaware.twproto.dataobjects.*;

public class TwLoadChildrenPanel extends javax.swing.JPanel {
	private TwWorkspace workspace = null;
	private TwWorkspace[] children = null;

	/** Creates new form TwLoadChildrenPanel */
	public TwLoadChildrenPanel() {
		initComponents();
	}

	public void setWorkspace(TwWorkspace ws) {
		workspace = ws;
		txtWorkspace.setText(workspace.getPath());
		setChildren();
	}

	private void setChildren() {
		wsList.removeAll();
		wsList.requestFocus();
		if (workspace != null) {
			TwWorkspace[] children = workspace.getChildren();
			Vector vecChildren = new Vector();
			if (children != null) {
				for (int i = 0; i < children.length; i++) {
					vecChildren.add(children[i]);
				}
			}
			wsList.setListData(vecChildren);
			wsList.requestFocus();
			if (vecChildren.size() > 0)
				wsList.setSelectedIndex(0);
			setButtons();
		}
	}

	private void setButtons() {
		int sz = wsList.getModel().getSize();
		if (sz == 0) {
			wsSelectAllButton.setEnabled(false);
			wsDeselectAllButton.setEnabled(false);
			return;
		}
		boolean selected = wsList.isSelectionEmpty();
		wsDeselectAllButton.setEnabled(!selected);
		wsSelectAllButton.setEnabled(selected
				|| (wsList.getSelectedValues().length < sz));
	}

	public TwWorkspace[] getSelection() {
		Object[] selValues = wsList.getSelectedValues();
		if (selValues != null) {
			children = new TwWorkspace[selValues.length];
			for (int i = 0; i < selValues.length; i++) {
				children[i] = (TwWorkspace) selValues[i];
			}
		}
		return children;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {// GEN-BEGIN:initComponents
		wsPanel = new javax.swing.JPanel();
		lblWorkspace = new javax.swing.JLabel();
		txtWorkspace = new javax.swing.JTextField();
		btnWorkspace = new javax.swing.JButton();
		listPanel = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		wsList = new javax.swing.JList();
		wsSelectAllButton = new javax.swing.JButton();
		wsDeselectAllButton = new javax.swing.JButton();
		lblList = new javax.swing.JLabel();

		setLayout(new java.awt.BorderLayout());

		setBorder(new javax.swing.border.EtchedBorder());
		wsPanel.setLayout(new java.awt.GridBagLayout());
		java.awt.GridBagConstraints gridBagConstraints1;

		wsPanel.setBorder(new javax.swing.border.EmptyBorder(
				new java.awt.Insets(4, 4, 4, 4)));
		lblWorkspace.setText("Parent Workspace");
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 0;
		gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
		wsPanel.add(lblWorkspace, gridBagConstraints1);

		txtWorkspace.setPreferredSize(new java.awt.Dimension(200, 21));
		txtWorkspace.setMinimumSize(new java.awt.Dimension(150, 21));
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 1;
		gridBagConstraints1.gridy = 0;
		gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
		wsPanel.add(txtWorkspace, gridBagConstraints1);

		btnWorkspace.setText("Browse");
		btnWorkspace.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnWorkspaceActionPerformed(evt);
			}
		});

		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 2;
		gridBagConstraints1.gridy = 0;
		wsPanel.add(btnWorkspace, gridBagConstraints1);

		add(wsPanel, java.awt.BorderLayout.NORTH);

		listPanel.setLayout(new java.awt.GridBagLayout());
		java.awt.GridBagConstraints gridBagConstraints2;

		listPanel.setBorder(new javax.swing.border.EmptyBorder(
				new java.awt.Insets(1, 4, 4, 4)));
		wsList.setPreferredSize(new java.awt.Dimension(250, 125));
		wsList.setMinimumSize(new java.awt.Dimension(200, 125));
		jScrollPane1.setViewportView(wsList);

		gridBagConstraints2 = new java.awt.GridBagConstraints();
		gridBagConstraints2.gridx = 0;
		gridBagConstraints2.gridy = 1;
		gridBagConstraints2.gridheight = 2;
		gridBagConstraints2.insets = new java.awt.Insets(0, 0, 0, 2);
		listPanel.add(jScrollPane1, gridBagConstraints2);

		wsSelectAllButton.setText("Select All");
		wsSelectAllButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						wsSelectAllButtonActionPerformed(evt);
					}
				});

		gridBagConstraints2 = new java.awt.GridBagConstraints();
		gridBagConstraints2.gridx = 1;
		gridBagConstraints2.gridy = 2;
		gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints2.anchor = java.awt.GridBagConstraints.NORTH;
		listPanel.add(wsSelectAllButton, gridBagConstraints2);

		wsDeselectAllButton.setText("Clear Selection");
		wsDeselectAllButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						wsDeselectAllButtonActionPerformed(evt);
					}
				});

		gridBagConstraints2 = new java.awt.GridBagConstraints();
		gridBagConstraints2.gridx = 1;
		gridBagConstraints2.gridy = 1;
		gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
		listPanel.add(wsDeselectAllButton, gridBagConstraints2);

		lblList.setText("Select Child Workspaces to load");
		lblList.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		gridBagConstraints2 = new java.awt.GridBagConstraints();
		gridBagConstraints2.gridx = 0;
		gridBagConstraints2.gridy = 0;
		gridBagConstraints2.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints2.anchor = java.awt.GridBagConstraints.WEST;
		listPanel.add(lblList, gridBagConstraints2);

		add(listPanel, java.awt.BorderLayout.CENTER);

	}// GEN-END:initComponents

	private void btnWorkspaceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnWorkspaceActionPerformed
		TwFileChooser chooser = new TwFileChooser();
		chooser.setType(TwFileChooser.WORKSPACE_CHOOSER);
		chooser.show();
		File file = chooser.getSelection();
		TwWorkspace ws = new TwWorkspaceObject(file.getAbsolutePath());
		setWorkspace(ws);
		setChildren();
	}// GEN-LAST:event_btnWorkspaceActionPerformed

	private void wsDeselectAllButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_wsDeselectAllButtonActionPerformed
		wsList.clearSelection();
		wsList.requestFocus();
	}// GEN-LAST:event_wsDeselectAllButtonActionPerformed

	private void wsSelectAllButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_wsSelectAllButtonActionPerformed
		int sz = wsList.getModel().getSize();
		if (sz > 0) {
			wsList.setSelectionInterval(0, sz - 1);
		}
		wsList.requestFocus();
	}// GEN-LAST:event_wsSelectAllButtonActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel wsPanel;
	private javax.swing.JLabel lblWorkspace;
	private javax.swing.JTextField txtWorkspace;
	private javax.swing.JButton btnWorkspace;
	private javax.swing.JPanel listPanel;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JList wsList;
	private javax.swing.JButton wsSelectAllButton;
	private javax.swing.JButton wsDeselectAllButton;
	private javax.swing.JLabel lblList;

	// End of variables declaration//GEN-END:variables
	public static void main(String[] args) {
		TwActionDialog actionDialog = new TwActionDialog(new JFrame(), true);
		TwLoadChildrenPanel trPanel = new TwLoadChildrenPanel();
		trPanel.setWorkspace(new com.nayaware.twproto.dataobjects.TwWorkspaceObject(
				"C:\\Test\\ws2"));
		actionDialog.setUserPanel(trPanel);
		actionDialog.show();
		// System.out.println(trPanel.getSelection());
	}
}
