/*
 * TwRenameWorkspacePanel.java
 * Author  Winston Prakash
 */

package com.nayaware.twproto.ui;

import javax.swing.*;
import java.util.*;

import com.nayaware.twproto.dataobjects.*;

public class TwRenameWorkspacePanel extends javax.swing.JPanel {

	/** Creates new form TwRenameWorkspacePanel */
	public TwRenameWorkspacePanel() {
		initComponents();
	}

	public void setWorkspace(TwWorkspace ws) {
		txtOldWs.setText(ws.getName());
	}

	public void setOldName(String oldName) {
		txtOldWs.setText(oldName);
	}

	public void setNewName(String oldName) {
		txtNewWs.setText(oldName);
	}

	public String getOldName() {
		return txtOldWs.getText();
	}

	public String getNewName() {
		return txtNewWs.getText();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {// GEN-BEGIN:initComponents
		renPanel = new javax.swing.JPanel();
		lblOldWs = new javax.swing.JLabel();
		txtOldWs = new javax.swing.JTextField();
		lblNewWs = new javax.swing.JLabel();
		txtNewWs = new javax.swing.JTextField();

		setLayout(new java.awt.BorderLayout());

		setBorder(new javax.swing.border.EtchedBorder());
		renPanel.setLayout(new java.awt.GridBagLayout());
		java.awt.GridBagConstraints gridBagConstraints1;

		renPanel.setBorder(new javax.swing.border.EmptyBorder(
				new java.awt.Insets(5, 5, 5, 5)));
		lblOldWs.setText("Old Workspace Name");
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 0;
		renPanel.add(lblOldWs, gridBagConstraints1);

		txtOldWs.setText(" ");
		txtOldWs.setPreferredSize(new java.awt.Dimension(200, 21));
		txtOldWs.setMinimumSize(new java.awt.Dimension(200, 21));
		txtOldWs.setEnabled(false);
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 1;
		gridBagConstraints1.gridy = 0;
		gridBagConstraints1.insets = new java.awt.Insets(0, 3, 0, 3);
		renPanel.add(txtOldWs, gridBagConstraints1);

		lblNewWs.setText("New Workspace Name");
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 1;
		renPanel.add(lblNewWs, gridBagConstraints1);

		txtNewWs.setPreferredSize(new java.awt.Dimension(200, 21));
		txtNewWs.setMinimumSize(new java.awt.Dimension(200, 21));
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 1;
		gridBagConstraints1.gridy = 1;
		gridBagConstraints1.insets = new java.awt.Insets(0, 3, 0, 3);
		renPanel.add(txtNewWs, gridBagConstraints1);

		add(renPanel, java.awt.BorderLayout.CENTER);

	}// GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel renPanel;
	private javax.swing.JLabel lblOldWs;
	private javax.swing.JTextField txtOldWs;
	private javax.swing.JLabel lblNewWs;
	private javax.swing.JTextField txtNewWs;

	// End of variables declaration//GEN-END:variables
	public static void main(String[] args) {
		TwActionDialog actionDialog = new TwActionDialog(new JFrame(), true);
		TwRenameWorkspacePanel trPanel = new TwRenameWorkspacePanel();
		trPanel.setWorkspace(new com.nayaware.twproto.dataobjects.TwWorkspaceObject(
				"C:\\Test\\ws2"));
		actionDialog.setUserPanel(trPanel);
		actionDialog.show();
		// System.out.println(trPanel.getSelection());
	}
}
