/*
 * TwReparentWorkspacePanel.java
 * Author  Winston Prakash
 * Created on August 2, 2001, 1:42 PM
 */

package com.nayaware.twproto.ui;

import java.io.*;
import javax.swing.*;

import com.nayaware.twproto.dataobjects.*;

public class TwReparentWorkspacePanel extends javax.swing.JPanel {

	private TwWorkspace child = null;
	private TwWorkspace parent = null;

	/** Creates new form TwReparentPanel */
	public TwReparentWorkspacePanel() {
		initComponents();

	}

	public void setWorkspace(TwWorkspace ws) {
		child = ws;
		txtChild.setText(child.getPath());
		parent = child.getParent();
		if (parent != null)
			txtParent.setText(parent.getPath());
	}

	public String getNewParent() {
		return txtParent.getText();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {// GEN-BEGIN:initComponents
		wsPanel = new javax.swing.JPanel();
		lblParent = new javax.swing.JLabel();
		txtParent = new javax.swing.JTextField();
		btnParent = new javax.swing.JButton();
		lblChild = new javax.swing.JLabel();
		txtChild = new javax.swing.JTextField();
		btnChild = new javax.swing.JButton();

		setLayout(new java.awt.BorderLayout());

		wsPanel.setLayout(new java.awt.GridBagLayout());
		java.awt.GridBagConstraints gridBagConstraints1;

		wsPanel.setBorder(new javax.swing.border.EtchedBorder());
		lblParent.setText("Parent Workspace");
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 0;
		gridBagConstraints1.insets = new java.awt.Insets(11, 5, 2, 5);
		wsPanel.add(lblParent, gridBagConstraints1);

		txtParent.setPreferredSize(new java.awt.Dimension(300, 21));
		txtParent.setMinimumSize(new java.awt.Dimension(300, 21));
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 1;
		gridBagConstraints1.gridy = 0;
		gridBagConstraints1.gridwidth = 7;
		gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints1.insets = new java.awt.Insets(10, 1, 2, 1);
		wsPanel.add(txtParent, gridBagConstraints1);

		btnParent.setText("Browse");
		btnParent.setPreferredSize(new java.awt.Dimension(60, 21));
		btnParent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		btnParent.setMargin(new java.awt.Insets(2, 5, 2, 5));
		btnParent.setMinimumSize(new java.awt.Dimension(60, 21));
		btnParent.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnParentActionPerformed(evt);
			}
		});

		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 8;
		gridBagConstraints1.gridy = 0;
		gridBagConstraints1.gridwidth = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints1.insets = new java.awt.Insets(10, 5, 2, 5);
		wsPanel.add(btnParent, gridBagConstraints1);

		lblChild.setText("Child Workspace");
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 1;
		gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints1.insets = new java.awt.Insets(3, 5, 5, 5);
		wsPanel.add(lblChild, gridBagConstraints1);

		txtChild.setText(" ");
		txtChild.setPreferredSize(new java.awt.Dimension(300, 21));
		txtChild.setMinimumSize(new java.awt.Dimension(300, 21));
		txtChild.setEnabled(false);
		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 1;
		gridBagConstraints1.gridy = 1;
		gridBagConstraints1.gridwidth = 7;
		gridBagConstraints1.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints1.insets = new java.awt.Insets(2, 1, 5, 1);
		wsPanel.add(txtChild, gridBagConstraints1);

		btnChild.setText("Browse");
		btnChild.setPreferredSize(new java.awt.Dimension(60, 21));
		btnChild.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		btnChild.setMargin(new java.awt.Insets(2, 5, 2, 5));
		btnChild.setMinimumSize(new java.awt.Dimension(60, 21));
		btnChild.setEnabled(false);
		btnChild.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnChildActionPerformed(evt);
			}
		});

		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 8;
		gridBagConstraints1.gridy = 1;
		gridBagConstraints1.insets = new java.awt.Insets(2, 5, 5, 5);
		wsPanel.add(btnChild, gridBagConstraints1);

		add(wsPanel, java.awt.BorderLayout.NORTH);

	}// GEN-END:initComponents

	private void btnChildActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnChildActionPerformed
		Runnable runnable = new Runnable() {
			public void run() {
				TwFileChooser chooser = new TwFileChooser();
				chooser.setType(TwFileChooser.WORKSPACE_CHOOSER);
				chooser.show();
				if (chooser.getSelection() != null) {
					txtChild.setText(chooser.getSelection().getAbsolutePath());
				}
			}
		};

		Thread thr = new Thread(runnable);
		thr.start();
	}// GEN-LAST:event_btnChildActionPerformed

	private void btnParentActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnParentActionPerformed
		Runnable runnable = new Runnable() {
			public void run() {
				TwFileChooser chooser = new TwFileChooser();
				chooser.setType(TwFileChooser.WORKSPACE_CHOOSER);
				chooser.show();
				if (chooser.getSelection() != null) {
					txtParent.setText(chooser.getSelection().getAbsolutePath());
				}
			}
		};

		Thread thr = new Thread(runnable);
		thr.start();
	}// GEN-LAST:event_btnParentActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel wsPanel;
	private javax.swing.JLabel lblParent;
	private javax.swing.JTextField txtParent;
	private javax.swing.JButton btnParent;
	private javax.swing.JLabel lblChild;
	private javax.swing.JTextField txtChild;
	private javax.swing.JButton btnChild;
	// End of variables declaration//GEN-END:variables

}
